# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SOPHIE'S WORLD
email:  
description: > # this means to ignore newlines until "baseurl:"
  What I'm writing when I'm not coding &ndash; or the other way around.
baseurl: "/sophies-world" # the subpath of your site, e.g. /blog
url: "http://sbchou.github.io" # the base hostname & protocol for your site
twitter_username: mpetitchou
github_username:   

# Build settings
markdown: kramdown

paginate: 1
paginator_path: "/sophies-world/page:num"